"""Bob Jenkins lookup3 ``nhash`` — Python port of WSJT-X's
``lib/wsprd/nhash.c``.

WSJT-X uses ``nhash(call, len(call), initval=146)`` as the basis for
the 22-bit / 15-bit / 12-bit / 10-bit hash values that compress
compound callsigns into FT4/FT8/WSPR packet payloads.  Both
``decode_ft8``-style and ``wsprd``-style decoders use the same
function with the same seed (146) — see
``/tmp/wsjtx-mirror/lib/wsprd/wsprd_utils.c:int unpk_(...)`` for the
WSPR-side call site and ``/tmp/wsjtx-mirror/lib/hash.f90`` for the
FT8/FT4 side.

This port matches the C output bit-exactly for ASCII inputs.
Cross-validation vectors are in ``tests/test_callhash_nhash.py``,
generated by compiling the upstream C and capturing its outputs.
"""
from __future__ import annotations

WSJTX_INITVAL = 146                   # Seed used by both jt9 and wsprd.
MASK22 = 0x3FFFFF                      # FT8/FT4 compound-call hash width.
MASK15 = 0x7FFF                        # WSPR Type 3 hash width.
MASK12 = 0xFFF                         # ARRL contest hash variant.
MASK10 = 0x3FF                         # Smallest WSJT-X hash variant.


def _rot(x: int, k: int) -> int:
    """32-bit rotate-left."""
    return ((x << k) | (x >> (32 - k))) & 0xFFFFFFFF


def _mix(a: int, b: int, c: int) -> tuple[int, int, int]:
    """The mix() macro from nhash.c — six rotate/xor/sub/add rounds."""
    a = (a - c) & 0xFFFFFFFF; a ^= _rot(c, 4);  c = (c + b) & 0xFFFFFFFF
    b = (b - a) & 0xFFFFFFFF; b ^= _rot(a, 6);  a = (a + c) & 0xFFFFFFFF
    c = (c - b) & 0xFFFFFFFF; c ^= _rot(b, 8);  b = (b + a) & 0xFFFFFFFF
    a = (a - c) & 0xFFFFFFFF; a ^= _rot(c, 16); c = (c + b) & 0xFFFFFFFF
    b = (b - a) & 0xFFFFFFFF; b ^= _rot(a, 19); a = (a + c) & 0xFFFFFFFF
    c = (c - b) & 0xFFFFFFFF; c ^= _rot(b, 4);  b = (b + a) & 0xFFFFFFFF
    return a, b, c


def _final(a: int, b: int, c: int) -> int:
    """The final() macro from nhash.c — seven rotate/xor/sub rounds."""
    c ^= b; c = (c - _rot(b, 14)) & 0xFFFFFFFF
    a ^= c; a = (a - _rot(c, 11)) & 0xFFFFFFFF
    b ^= a; b = (b - _rot(a, 25)) & 0xFFFFFFFF
    c ^= b; c = (c - _rot(b, 16)) & 0xFFFFFFFF
    a ^= c; a = (a - _rot(c,  4)) & 0xFFFFFFFF
    b ^= a; b = (b - _rot(a, 14)) & 0xFFFFFFFF
    c ^= b; c = (c - _rot(b, 24)) & 0xFFFFFFFF
    return c


def nhash(key: bytes | str, initval: int = WSJTX_INITVAL) -> int:
    """Compute Bob Jenkins lookup3 hash of ``key`` with the given seed.

    Matches the C output of WSJT-X's ``nhash()`` for ASCII inputs.
    Returns a 32-bit unsigned integer; callers mask down to the bit
    width their protocol uses (see :func:`hash22`, :func:`hash15`).

    ``key`` may be ``bytes`` or ``str``; strings are encoded as ASCII
    (matching the C call sites that hash Fortran character arrays
    containing callsign text).
    """
    if isinstance(key, str):
        key = key.encode("ascii")
    length = len(key)
    a = b = c = (0xDEADBEEF + length + initval) & 0xFFFFFFFF

    # Process complete 12-byte blocks as three little-endian uint32s.
    pos = 0
    remaining = length
    while remaining > 12:
        a = (a + int.from_bytes(key[pos      : pos + 4],  "little")) & 0xFFFFFFFF
        b = (b + int.from_bytes(key[pos + 4  : pos + 8],  "little")) & 0xFFFFFFFF
        c = (c + int.from_bytes(key[pos + 8  : pos + 12], "little")) & 0xFFFFFFFF
        a, b, c = _mix(a, b, c)
        remaining -= 12
        pos += 12

    # Final partial block — emulate the C switch statement, masking
    # so the output matches the C's "read-past-end-then-mask" trick
    # (we just don't read past the end).  Zero-length input returns
    # the initial c verbatim.
    if remaining == 0:
        return c

    tail = key[pos : pos + remaining]
    if remaining >= 9:
        a = (a + int.from_bytes(tail[0:4],   "little")) & 0xFFFFFFFF
        b = (b + int.from_bytes(tail[4:8],   "little")) & 0xFFFFFFFF
        c_val = int.from_bytes(tail[8:remaining], "little")
        c = (c + c_val) & 0xFFFFFFFF
    elif remaining >= 5:
        a = (a + int.from_bytes(tail[0:4],   "little")) & 0xFFFFFFFF
        b_val = int.from_bytes(tail[4:remaining], "little")
        b = (b + b_val) & 0xFFFFFFFF
    else:
        a_val = int.from_bytes(tail[:remaining], "little")
        a = (a + a_val) & 0xFFFFFFFF

    return _final(a, b, c)


def hash22(call: str) -> int:
    """22-bit hash of ``call`` — used by FT8/FT4 compound-callsign packets."""
    return nhash(call) & MASK22


def hash15(call: str) -> int:
    """15-bit hash of ``call`` — used by WSPR Type 3 packets."""
    return nhash(call) & MASK15


def hash12(call: str) -> int:
    """12-bit hash variant — used by some ARRL-contest message types."""
    return nhash(call) & MASK12


def hash10(call: str) -> int:
    """10-bit hash variant — narrowest WSJT-X hash."""
    return nhash(call) & MASK10
